version: "3.9"
services:
        mysqldb:
            image: mysql
            container_name: meu-mysql
            environment:
                - MYSQL_ROOT_PASSWORD=ribasnight8426
            volumes:
                - agendamento_volume:/var/lib/mysql
            networks:
                - compose-bridge   
        agendamento:
            image: ribeiroribas/agendamento
            container_name: app_agendamento
            environment:
                - SPRING_PROFILES_ACTIVE=prod
                - AGENDAMENTO_DATABASE_URL=jdbc:mysql://172.19.0.2:3306/agendamento_db
                - AGENDAMENTO_DATABASE_USERNAME=root
                - AGENDAMENTO_DATABASE_PASSWORD=ribasnight8426
                - AGENDAMENTO_JWT_SECRET=ribasnight8426
                - PORT=8081
            networks:
                - compose-bridge
            ports:
                - 8082:8081 
            depends_on:
                - mysqldb
volumes:
    agendamento_volume:
        external: false
networks:
  compose-bridge:
    driver: bridge